version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: |
      sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 $MINIO_USER $MINIO_PASSWORD &&
      mc mb myminio/silver &&
      mc mb myminio/gold
      "

  trino-coordinator:
    container_name: trino
    image: trinodb/trino:468
    hostname: trino-coordinator
    ports:
      - 8085:8080
    depends_on:
      - minio-mc
    volumes:
      - ./src/trino/etc:/etc/trino
    environment:
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}

  trino-worker:
    image: trinodb/trino:468
    container_name: trino-worker
    hostname: trino-worker
    depends_on:
      - trino-coordinator
    volumes:
      - ./src/trino/etc:/etc/trino
    environment:
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}

  trino-init:
    image: trinodb/trino:468
    depends_on:
      - trino-coordinator
    entrypoint: [ "/bin/sh", "-c", "sleep 30 && trino --server trino-coordinator:8080 -f /docker-entrypoint-initdb.d/create_schemas.sql" ]
    volumes:
      - ./src/trino/init_trino/create_schemas.sql:/docker-entrypoint-initdb.d/create_schemas.sql

  mariadb:
    container_name: mariadb
    hostname: metastore_db
    image: mariadb:10.5.8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - 9083:9083 # Metastore Thrift
    volumes:
      - ./src/hive/config/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
      HIVE_METASTORE_DRIVER: org.mariadb.jdbc.Driver
    depends_on:
      - mariadb

volumes:
  minio-data:
