spark_config:
    spark.executor.memory: "8g"
    spark.executor.cores: "4"
    spark.driver.memory: "4g"
    spark.executor.memoryOverhead: "1g"
    spark.driver.memoryOverhead: "1g"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.hadoop.fs.s3a.endpoint: "${MINIO_ENDPOINT}"
    spark.hadoop.fs.s3a.access.key: "${MINIO_USER}"
    spark.hadoop.fs.s3a.secret.key: "${MINIO_PASSWORD}"
    spark.local.dir: "/tmp"
    spark.storage.tempDIR: "/tmp"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.path.style.access: "true"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
